# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-06 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_onetooneclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFieldSaveClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
