# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-15 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_requestfieldsaveclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='childclass',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
