# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-15 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20180515_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_applications', to='test_app.Application'),
        ),
        migrations.AlterField(
            model_name='communityapplication',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_applications', to='test_app.Community'),
        ),
    ]
