# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework_simplify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_modelwithparentresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedClassNoDisplayChars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encrypted_val', rest_framework_simplify.fields.SimplifyEncryptedCharField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
