# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-16 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_encryptedclassnodisplaychars'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclass',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
