# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_basicclass_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicclass',
            name='binary_field',
            field=models.BinaryField(blank=True, default=b'binarystring', null=True),
        ),
    ]
