# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-26 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework_simplify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_basicclass_binary_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTextFieldClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_text', rest_framework_simplify.fields.SimplifyJsonTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
