# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-26 17:38
from __future__ import unicode_literals

from django.db import migrations
import rest_framework_simplify.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_jsontextfieldclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsontextfieldclass',
            name='json_text',
            field=rest_framework_simplify.fields.SimplifyJsonTextField(blank=True, null=True),
        ),
    ]
