# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-08 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_auto_20190726_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithparentresource',
            name='basic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_with_parent_resources', to='test_app.BasicClass'),
        ),
    ]
