# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-12-08 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_auto_20190726_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestedChild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_one', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_child', to='test_app.ChildClass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
