# Generated by Django 4.2.8 on 2024-10-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_nestedchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
