# Generated by Django 4.2.8 on 2024-10-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0015_childclass_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelwithparentresource",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
