import logging
from typing import TypedDict

from django.conf import settings
from django.http import Http404, QueryDict
from django.core.exceptions import PermissionDenied
from rest_framework import exceptions, status
from rest_framework.response import Response
from rest_framework.request import Request


class _Context(TypedDict):
    request: Request


def exception_handler(exc: Exception, context: _Context) -> Response:
    """
    exception_handler logs detailed exceptions and returns generic messages to consumers. The
    messages are vague for security reasons.

    Exceptions extending APIException are able to pass through messages with the default_detail
    field and status codes with the status_code field.

    Django's Http404 and PermissionDenied are translated to Rest Framework's NotFound and
    PermissionDenied.

    NotAuthenticated and AuthenticationFailed are coerced to a 403 status.

    Logs generated by the exception_handler may contain sensitive data in the request body and
    query params fields. This data can be masked with:
    - rest_framework_simplify.decorators.sensitive_rq_data
    - rest_framework_simplify.decorators.sensitive_rq_query_params

    By default, log extras use prefixed field names (rq_method, rq_path, etc.). Set the Django
    setting DRF_SIMPLIFY_LOG_STANDARD_FIELDS = True to emit standardized names instead (method,
    endpoint, query_params, request_data, status_code, exception_type, exception_detail).
    """
    # Historically, 400 has been the default instead of 500.
    status_code = status.HTTP_400_BAD_REQUEST
    error_message = exceptions.APIException.default_detail

    exc = _django_to_rest_framework(exc)

    if isinstance(exc, exceptions.APIException):
        status_code = exc.status_code
        # default_detail is chosen over detail in order to not expose too much information.
        error_message = exc.default_detail

    _log_exception(exc, context, status_code, error_message)

    return Response({ 'errorMessage': error_message }, status=status_code)


REDACT_MESSAGE = f'**Redacted by {exception_handler.__module__}.{exception_handler.__name__}**'


def _django_to_rest_framework(exc: Exception):
    if isinstance(exc, Http404):
        return exceptions.NotFound(*exc.args)
    if isinstance(exc, PermissionDenied):
        return exceptions.PermissionDenied(*exc.args)
    return exc


_STANDARD_FIELDS = {
    'query_params': 'query_params',
    'request_data': 'request_data',
    'method': 'method',
    'path': 'endpoint',
    'status_code': 'status_code',
    'exception_type': 'exception_type',
    'exception_detail': 'exception_detail',
}

_LEGACY_FIELDS = {
    'query_params': 'rq_query_params',
    'request_data': 'rq_data',
    'method': 'rq_method',
    'path': 'rq_path',
    'status_code': 'rs_status_code',
    'exception_type': 'exc_first_arg',
    'exception_detail': 'exc_detail',
}


def _log_exception(exc: Exception, context: _Context, status_code: int, error_message: str):
    logger = logging.getLogger('rest-framework-simplify-exception')
    use_standard = getattr(settings, 'DRF_SIMPLIFY_LOG_STANDARD_FIELDS', False)
    field_names = _STANDARD_FIELDS if use_standard else _LEGACY_FIELDS

    extra = {
        field_names['query_params']: _get_redacted_rq_query_params(exc, context),
        field_names['request_data']: _get_redacted_rq_data(exc, context),
        field_names['method']: context['request'].method,
        field_names['path']: context['request'].path,
        field_names['status_code']: status_code,
        field_names['exception_type']: exc.args[0] if exc.args else None,
        field_names['exception_detail']: exc.detail if isinstance(exc, exceptions.APIException) else None,
    }
    logger.exception(error_message, extra=extra)


def _get_redacted_rq_data(exc: Exception, context: _Context):
    if not hasattr(exc, '_sensitive_rq_data_keys'):
        return context['request'].data
    qd = context['request'].data
    if isinstance(context['request'].data, QueryDict):
        qd = context['request'].data.copy()
    sensitive_keys = [_to_canonical(k) for k in exc._sensitive_rq_data_keys]
    for k in qd.keys():
        if _to_canonical(k) in sensitive_keys:
            qd[k] = REDACT_MESSAGE
    return qd


def _get_redacted_rq_query_params(exc: Exception, context: _Context):
    if not hasattr(exc, '_sensitive_rq_query_params'):
        return context['request'].query_params
    qd = context['request'].query_params.copy()
    sensitive_keys = [_to_canonical(k) for k in exc._sensitive_rq_query_params]
    for k in qd.keys():
        if _to_canonical(k) in sensitive_keys:
            qd[k] = REDACT_MESSAGE
    return qd


# _to_canonical solves the issue of snake case and camel case being supported. By lowering and
# stripping underscores, we cover keys in any format.
def _to_canonical(key):
    return key.replace('_', '').lower()
