# Generated by Django 3.2.23 on 2023-12-27 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rest_framework_simplify.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('binary_field', models.BinaryField(blank=True, default=b'binarystring', null=True)),
                ('exclude_field', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncryptedClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encrypted_val', rest_framework_simplify.fields.SimplifyEncryptedCharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncryptedClassNoDisplayChars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encrypted_val', rest_framework_simplify.fields.SimplifyEncryptedCharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JsonTextFieldClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_text', rest_framework_simplify.fields.SimplifyJsonTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaDataClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], default='two', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelWithSensitiveData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_text', models.CharField(blank=True, max_length=32, null=True)),
                ('top_secret', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneToOneClass',
            fields=[
                ('alternative_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhaseGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestFieldSaveClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NestedChild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_one', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_child', to='tests.childclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelWithParentResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_field', models.CharField(blank=True, max_length=32, null=True)),
                ('basic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.basicclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkingClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linking_classes', to='tests.basicclass')),
                ('child_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linking_classes', to='tests.childclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_applications', to='tests.application')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_applications', to='tests.community')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='community',
            name='phase_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='tests.phasegroup'),
        ),
        migrations.AddField(
            model_name='basicclass',
            name='child_one',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_class_one', to='tests.childclass'),
        ),
        migrations.AddField(
            model_name='basicclass',
            name='child_three',
            field=models.ManyToManyField(blank=True, null=True, related_name='basic_class_three', to='tests.ChildClass'),
        ),
        migrations.AddField(
            model_name='basicclass',
            name='child_two',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_class_two', to='tests.childclass'),
        ),
        migrations.AddField(
            model_name='basicclass',
            name='model_with_sensitive_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.modelwithsensitivedata'),
        ),
    ]
