name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
    services:
      postgres:
        image: cimg/postgres:12.8
        env:
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'

      - run: sudo apt-get update

      - run: |
          sudo apt-get install postgresql-client
          createuser test -h localhost -U postgres -d
          createdb -h localhost -U postgres drfsimp -O test
          createdb -h localhost -U postgres drfsimp_rr -O test

      - uses: actions/cache/restore@v4
        with:
          path: ./venv
          key: v1-dependencies-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            v1-dependencies-

      - name: Install FreeTDS
        run: |
          sudo apt-get update && sudo apt-get install freetds-dev libssl-dev

      - name: install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions/cache/save@v4
        with:
          path: ./venv
          key: v1-dependencies-${{ hashFiles('requirements.txt') }}

      - name: run migrations
        run: |
          . venv/bin/activate
          python manage.py migrate
          python manage.py migrate --database=readreplica

      - name: run tests
        run: |
          mkdir xunit
          . venv/bin/activate
          python manage.py test

      - name: PyPi Deploy
        env:
          CIRCLE_BRANCH: ${{ github.ref_name }}
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            pip install --upgrade pip build
            pip install twine
            python -m build
            twine upload --username __token__ --password "${PYPI_API_TOKEN}" dist/*
          fi